version: '3'
services:
  my_client_1:
    image: yashgt/client:latest
    build: ../client
    #restart: on-failure:3    
    volumes:
    - serverlog:/log
    depends_on:
    - my_server    
    labels:
        - "constraint:node==default"    
    environment:
        - "constraint:node==default"    
    networks:
    - mynet        
  my_server:
    image: yashgt/proc1:latest
    #image: gophernet/netcat
    command: "2"   
    expose:
     - "5000"    
    build: ../proc1
    #restart: on-failure:3    
    volumes:
    - serverlog:/log
    labels:
        - "constraint:node==gol05854"    
    environment:
        - "constraint:node==gol05854"    
    networks:
    - mynet        
volumes:
    serverlog:
         driver: local
networks:
    mynet:
        driver: overlay    
