version: '3'
services:
 my_client_1:
    image: yashgt/client:latest
    build: ../client
    #restart: on-failure:3
    volumes:
    - serverlog:/log
    depends_on:
    - my_server    
        
    networks:
    - mynet


    deploy:
      placement:
        constraints:
        - node.hostname == gol05854

 my_server:
    image: yashgt/proc1:latest
    #image: gophernet/netcat
    command: ["3"]
    expose:
     - "5000"
    build: ../proc1
    #restart: on-failure:3
    volumes:
    - serverlog:/log
    deploy:
        placement:
                constraints:
                        - node.hostname == gol05854

    #Container will start with these env vars
    #$ENAME is set when invoking compose/deploy
    environment:
        - ENAME=${ENAME}

    networks:
    - mynet
volumes:
    serverlog:
         driver: local
networks:
    mynet:
        driver: overlay
