FROM alpine
RUN apt-get -y update
#RUN apt-get install -y netcat
#COPY ncat ./nc
RUN apt-get install -y oracle-java7-installer

#ARG rpm_dir=rpm
#ENV rpm_dir=$rpm_dir  

#RUN mkdir rpm
#COPY ${rpm_dir}/jre-7u79-linux-x64.rpm rpm/
#RUN rpm -i rpm/jre-7u79-linux-x64.rpm

